updating

diff --git a/mygit b/mygit
--- a/mygit
+++ b/mygit
@@ -1,11 +1,21 @@
 #!/usr/bin/env bash
 
 git pull
+
+pull=$?
+
+if [[ "$pull" -ne 0 ]]
+then
+        echo "Fix git pull error as seen in the following output, and run script again"
+        echo "$pull"
+        exit 1
+fi
+
 git add .
 
 # Prompt for commit message
 echo "Please enter your commit message: "
-read message
+read -r message
 
 git commit -m "$message"
-git push
+git push
